### ISSUE TITLE
Understanding the address you wrote to SLAVE

### ISSUE THREAD

**Issue by gentunian** [Tinee9/LIS2HH12TR#2]
Hi, :) I'm following your guide for arduino and LIS2HH12TR accelerometer.

I'm also reading the [LIS2HH12TR datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/c9/16/f2/79/ca/31/47/89/DM00096789.pdf/files/DM00096789.pdf/jcr:content/translations/en.DM00096789.pdf), and I'm having hard time to understand [this line](https://github.com/Tinee9/LIS2HH12TR/blob/c2567b61f9bc0b14e810043905e638b065af7961/Tiny9_LIS2HH12.cpp#L93) of your code.

Setting GND to SA0 should make the salve adress 30 (11110b), but not sure why before reading you are making this:

```c
Wire.beginTransmission(LIS2HH12_DEVICE);  
Wire.write(address);             
Wire.endTransmission(); 
```

with `address` being 40.

I hope you still read this repo :)

**Comment by Tinee9** [comment]
Thanks for following me. I apologize for not getting back to your comment/question as I haven't gotten notifications for comments to my repository. I have noticed an uptick in people working with this Module so I plan to be more attentive. I do agree there was something that was odd about the address difference from SPEC and what I implemented. I will be taking a closer look at the Code and see why I chose this route.

**Comment by Tinee9** [comment]
Gentunian,
The reason why I have address being Dec 40 is because that is where in Memory the X ,Y, and Z Values are stored by the Accelerometer. 30 yes is indeed the address to start the Slave communication but that is done with Begin Transmission line above.
